# Generated by Django 5.1.3 on 2024-12-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medal1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='medal2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='medal3',
            field=models.BooleanField(default=False),
        ),
    ]
