# Generated by Django 5.1.3 on 2024-12-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_medal1_profile_medal2_profile_medal3'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='пустое описание'),
        ),
    ]
